[package]
name = "profiler"
version.workspace = true
edition.workspace = true

[dependencies]
core = { path = "../core" }
storage = { path = "../storage" }
polars.workspace = true
arrow.workspace = true
anyhow.workspace = true
serde.workspace = true
tracing.workspace = true
parking_lot.workspace = true
