[package]
name = "app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "split_office"
path = "src/main.rs"

[dependencies]
core = { path = "../crates/core" }
storage = { path = "../crates/storage" }
query = { path = "../crates/query" }
grid = { path = "../crates/grid" }
profiler = { path = "../crates/profiler" }
workflow = { path = "../crates/workflow" }
document_core = { path = "../crates/document_core" }
document_view = { path = "../crates/document_view" }
cdm = { path = "../crates/cdm" }
workspace_core = { path = "../crates/workspace_core" }
split_view     = { path = "../crates/split_view" }
eframe.workspace = true
egui.workspace = true
arrow.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
rfd = "0.15"
polars.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
